export const countries = [
    { code: 'US', name: 'United States', region: 'North America' },
    { code: 'IN', name: 'India', region: 'Asia' },
    { code: 'DE', name: 'Germany', region: 'Europe' },
    { code: 'UK', name: 'United Kingdom', region: 'Europe' },
    { code: 'JP', name: 'Japan', region: 'Asia' },
    { code: 'CN', name: 'China', region: 'Asia' },
    { code: 'AU', name: 'Australia', region: 'Oceania' },
    { code: 'BR', name: 'Brazil', region: 'South America' },
    { code: 'AE', name: 'United Arab Emirates', region: 'Middle East' },
    { code: 'KR', name: 'South Korea', region: 'Asia' }
];

export const manufacturers = [
    { id: 'toyota', name: 'Toyota', country_origin: 'JP' },
    { id: 'tata', name: 'Tata Motors', country_origin: 'IN' },
    { id: 'tesla', name: 'Tesla', country_origin: 'US' },
    { id: 'ford', name: 'Ford', country_origin: 'US' },
    { id: 'bmw', name: 'BMW', country_origin: 'DE' },
    { id: 'byd', name: 'BYD', country_origin: 'CN' },
    { id: 'volkswagen', name: 'Volkswagen', country_origin: 'DE' },
    { id: 'maruti-suzuki', name: 'Maruti Suzuki', country_origin: 'IN' },
    { id: 'mahindra', name: 'Mahindra', country_origin: 'IN' },
    { id: 'hyundai', name: 'Hyundai', country_origin: 'KR' },
    { id: 'chevrolet', name: 'Chevrolet', country_origin: 'US' },
    { id: 'mercedes-benz', name: 'Mercedes-Benz', country_origin: 'DE' },
    { id: 'audi', name: 'Audi', country_origin: 'DE' },
    { id: 'honda', name: 'Honda', country_origin: 'JP' },
    { id: 'nissan', name: 'Nissan', country_origin: 'JP' },
    { id: 'geely', name: 'Geely', country_origin: 'CN' }
];


export const models = [
    { id: 'toyota-corolla', manufacturer_id: 'toyota', name: 'Corolla', body_type: 'Sedan' },
    { id: 'toyota-rav4', manufacturer_id: 'toyota', name: 'RAV4', body_type: 'SUV' },
    { id: 'toyota-hilux', manufacturer_id: 'toyota', name: 'Hilux', body_type: 'Pickup' },
    { id: 'tata-nexon', manufacturer_id: 'tata', name: 'Nexon', body_type: 'SUV' },
    { id: 'tata-harrier', manufacturer_id: 'tata', name: 'Harrier', body_type: 'SUV' },
    { id: 'tata-tiago', manufacturer_id: 'tata', name: 'Tiago', body_type: 'Hatchback' },
    { id: 'tesla-model-3', manufacturer_id: 'tesla', name: 'Model 3', body_type: 'Sedan' },
    { id: 'tesla-model-y', manufacturer_id: 'tesla', name: 'Model Y', body_type: 'SUV' },
    { id: 'tesla-cybertruck', manufacturer_id: 'tesla', name: 'Cybertruck', body_type: 'Pickup' },
    { id: 'ford-f-150', manufacturer_id: 'ford', name: 'F-150', body_type: 'Pickup' },
    { id: 'ford-mustang', manufacturer_id: 'ford', name: 'Mustang', body_type: 'Coupe' },
    { id: 'ford-ranger', manufacturer_id: 'ford', name: 'Ranger', body_type: 'Pickup' },
    { id: 'bmw-3-series', manufacturer_id: 'bmw', name: '3 Series', body_type: 'Sedan' },
    { id: 'bmw-x5', manufacturer_id: 'bmw', name: 'X5', body_type: 'SUV' },
    { id: 'bmw-i4', manufacturer_id: 'bmw', name: 'i4', body_type: 'Sedan' },
    { id: 'byd-atto-3', manufacturer_id: 'byd', name: 'Atto 3', body_type: 'SUV' },
    { id: 'byd-seal', manufacturer_id: 'byd', name: 'Seal', body_type: 'Sedan' },
    { id: 'byd-dolphin', manufacturer_id: 'byd', name: 'Dolphin', body_type: 'Hatchback' },
    { id: 'volkswagen-golf', manufacturer_id: 'volkswagen', name: 'Golf', body_type: 'Hatchback' },
    { id: 'volkswagen-tiguan', manufacturer_id: 'volkswagen', name: 'Tiguan', body_type: 'SUV' },
    { id: 'volkswagen-polo', manufacturer_id: 'volkswagen', name: 'Polo', body_type: 'Hatchback' },
    { id: 'maruti-suzuki-swift', manufacturer_id: 'maruti-suzuki', name: 'Swift', body_type: 'Hatchback' },
    { id: 'maruti-suzuki-brezza', manufacturer_id: 'maruti-suzuki', name: 'Brezza', body_type: 'SUV' },
    { id: 'maruti-suzuki-grand-vitara', manufacturer_id: 'maruti-suzuki', name: 'Grand Vitara', body_type: 'SUV' },
    { id: 'mahindra-scorpio-n', manufacturer_id: 'mahindra', name: 'Scorpio-N', body_type: 'SUV' },
    { id: 'mahindra-xuv700', manufacturer_id: 'mahindra', name: 'XUV700', body_type: 'SUV' },
    { id: 'mahindra-thar', manufacturer_id: 'mahindra', name: 'Thar', body_type: 'SUV' },
    { id: 'hyundai-creta', manufacturer_id: 'hyundai', name: 'Creta', body_type: 'SUV' },
    { id: 'hyundai-ioniq-5', manufacturer_id: 'hyundai', name: 'IONIQ 5', body_type: 'SUV' },
    { id: 'hyundai-tucson', manufacturer_id: 'hyundai', name: 'Tucson', body_type: 'SUV' },
    { id: 'toyota-camry', manufacturer_id: 'toyota', name: 'Camry', body_type: 'Sedan' },
    { id: 'tesla-model-s', manufacturer_id: 'tesla', name: 'Model S', body_type: 'Sedan' },
    { id: 'tesla-model-x', manufacturer_id: 'tesla', name: 'Model X', body_type: 'SUV' },
    { id: 'chevrolet-corvette', manufacturer_id: 'chevrolet', name: 'Corvette Stingray', body_type: 'Coupe' },
    { id: 'chevrolet-silverado', manufacturer_id: 'chevrolet', name: 'Silverado 1500', body_type: 'Pickup' },
    { id: 'mercedes-benz-c-class', manufacturer_id: 'mercedes-benz', name: 'C-Class', body_type: 'Sedan' },
    { id: 'mercedes-benz-eqe', manufacturer_id: 'mercedes-benz', name: 'EQE SUV', body_type: 'EV' },
    { id: 'audi-a4', manufacturer_id: 'audi', name: 'A4 Sedan', body_type: 'Sedan' },
    { id: 'audi-e-tron-gt', manufacturer_id: 'audi', name: 'e-tron GT', body_type: 'EV' },
    { id: 'honda-civic', manufacturer_id: 'honda', name: 'Civic', body_type: 'Sedan' },
    { id: 'honda-cr-v', manufacturer_id: 'honda', name: 'CR-V', body_type: 'SUV' },
    { id: 'nissan-gt-r', manufacturer_id: 'nissan', name: 'GT-R', body_type: 'Coupe' },
    { id: 'nissan-ariya', manufacturer_id: 'nissan', name: 'Ariya', body_type: 'EV' },
    { id: 'geely-coolray', manufacturer_id: 'geely', name: 'Coolray', body_type: 'SUV' }
];


export const trims = [
    // Toyota Corolla
    {
        id: 'toyota-corolla-us-le',
        model_id: 'toyota-corolla',
        country_code: 'US',
        trim_name: 'LE',
        year: 2024,
        engine: '2.0L 4-Cylinder DOHC',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 169,
        price_local: '$22,050',
        on_sale: 1
    },
    {
        id: 'toyota-corolla-us-se',
        model_id: 'toyota-corolla',
        country_code: 'US',
        trim_name: 'SE',
        year: 2024,
        engine: '2.0L 4-Cylinder DOHC',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 169,
        price_local: '$24,490',
        on_sale: 1
    },
    {
        id: 'toyota-corolla-us-xse',
        model_id: 'toyota-corolla',
        country_code: 'US',
        trim_name: 'XSE',
        year: 2024,
        engine: '2.0L 4-Cylinder DOHC',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 169,
        price_local: '$27,150',
        on_sale: 1
    },
    {
        id: 'toyota-corolla-jp-g',
        model_id: 'toyota-corolla',
        country_code: 'JP',
        trim_name: 'G Hybrid',
        year: 2024,
        engine: '1.8L Hybrid',
        transmission: 'eCVT',
        drivetrain: 'FWD',
        fuel_type: 'Hybrid',
        power_hp: 140,
        price_local: '¥2,450,000',
        on_sale: 1
    },
    {
        id: 'toyota-corolla-jp-wxb',
        model_id: 'toyota-corolla',
        country_code: 'JP',
        trim_name: 'W×B Hybrid',
        year: 2024,
        engine: '1.8L Hybrid',
        transmission: 'eCVT',
        drivetrain: 'E-Four',
        fuel_type: 'Hybrid',
        power_hp: 140,
        price_local: '¥2,850,000',
        on_sale: 1
    },
    {
        id: 'toyota-corolla-uk-icon',
        model_id: 'toyota-corolla',
        country_code: 'UK',
        trim_name: 'Icon 1.8 Hybrid',
        year: 2024,
        engine: '1.8L Hybrid',
        transmission: 'eCVT',
        drivetrain: 'FWD',
        fuel_type: 'Hybrid',
        power_hp: 138,
        price_local: '£30,500',
        on_sale: 1
    },
    {
        id: 'toyota-corolla-au-ascent',
        model_id: 'toyota-corolla',
        country_code: 'AU',
        trim_name: 'Ascent Sport',
        year: 2024,
        engine: '2.0L 4-Cylinder',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 169,
        price_local: 'A$32,110',
        on_sale: 1
    },
    {
        id: 'toyota-corolla-ae-xli',
        model_id: 'toyota-corolla',
        country_code: 'AE',
        trim_name: 'XLI 2.0',
        year: 2024,
        engine: '2.0L 4-Cylinder',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 168,
        price_local: 'AED 74,900',
        on_sale: 1
    },

    // Toyota RAV4
    {
        id: 'toyota-rav4-us-xle',
        model_id: 'toyota-rav4',
        country_code: 'US',
        trim_name: 'XLE AWD',
        year: 2024,
        engine: '2.5L 4-Cylinder',
        transmission: '8-Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 203,
        price_local: '$31,535',
        on_sale: 1
    },
    {
        id: 'toyota-rav4-de-comfort',
        model_id: 'toyota-rav4',
        country_code: 'DE',
        trim_name: 'Comfort Hybrid',
        year: 2024,
        engine: '2.5L Hybrid',
        transmission: 'eCVT',
        drivetrain: 'FWD',
        fuel_type: 'Hybrid',
        power_hp: 218,
        price_local: '€40,990',
        on_sale: 1
    },
    {
        id: 'toyota-rav4-au-gxl',
        model_id: 'toyota-rav4',
        country_code: 'AU',
        trim_name: 'GXL Hybrid 2WD',
        year: 2024,
        engine: '2.5L Hybrid',
        transmission: 'eCVT',
        drivetrain: 'FWD',
        fuel_type: 'Hybrid',
        power_hp: 215,
        price_local: 'A$46,950',
        on_sale: 1
    },

    // Toyota Hilux
    {
        id: 'toyota-hilux-au-sr5',
        model_id: 'toyota-hilux',
        country_code: 'AU',
        trim_name: 'SR5 Double Cab 4x4',
        year: 2024,
        engine: '2.8L Turbo Diesel',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Diesel',
        power_hp: 201,
        price_local: 'A$62,490',
        on_sale: 1
    },
    {
        id: 'toyota-hilux-br-srx',
        model_id: 'toyota-hilux',
        country_code: 'BR',
        trim_name: 'SRX Plus 4x4',
        year: 2024,
        engine: '2.8L Turbo Diesel',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Diesel',
        power_hp: 204,
        price_local: 'R$ 334,890',
        on_sale: 1
    },
    {
        id: 'toyota-hilux-ae-adventure',
        model_id: 'toyota-hilux',
        country_code: 'AE',
        trim_name: 'Adventure 4.0L V6',
        year: 2024,
        engine: '4.0L V6 Petrol',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Gasoline',
        power_hp: 235,
        price_local: 'AED 152,900',
        on_sale: 1
    },

    // Tata Nexon
    {
        id: 'tata-nexon-in-smart',
        model_id: 'tata-nexon',
        country_code: 'IN',
        trim_name: 'Smart 1.2 Petrol',
        year: 2024,
        engine: '1.2L Turbocharged Revotron',
        transmission: '5-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 120,
        price_local: '₹7,99,990',
        on_sale: 1
    },
    {
        id: 'tata-nexon-in-fearless',
        model_id: 'tata-nexon',
        country_code: 'IN',
        trim_name: 'Fearless Plus S 1.2 DCA',
        year: 2024,
        engine: '1.2L Turbocharged Revotron',
        transmission: '7-Speed DCA',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 120,
        price_local: '₹14,99,900',
        on_sale: 1
    },
    {
        id: 'tata-nexon-in-creative-diesel',
        model_id: 'tata-nexon',
        country_code: 'IN',
        trim_name: 'Creative Plus 1.5 Diesel AMT',
        year: 2024,
        engine: '1.5L Turbocharged Revotorq',
        transmission: '6-Speed AMT',
        drivetrain: 'FWD',
        fuel_type: 'Diesel',
        power_hp: 115,
        price_local: '₹13,50,000',
        on_sale: 1
    },
    {
        id: 'tata-nexon-in-ev-empowered',
        model_id: 'tata-nexon',
        country_code: 'IN',
        trim_name: 'EV Empowered Plus LR',
        year: 2024,
        engine: 'Permanent Magnet Synchronous AC Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 143,
        price_local: '₹19,29,000',
        on_sale: 1
    },

    // Tata Harrier
    {
        id: 'tata-harrier-in-pure',
        model_id: 'tata-harrier',
        country_code: 'IN',
        trim_name: 'Pure Plus',
        year: 2024,
        engine: '2.0L Kryotec Turbo Diesel',
        transmission: '6-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Diesel',
        power_hp: 170,
        price_local: '₹18,69,000',
        on_sale: 1
    },
    {
        id: 'tata-harrier-in-fearless',
        model_id: 'tata-harrier',
        country_code: 'IN',
        trim_name: 'Fearless Plus Dark AT',
        year: 2024,
        engine: '2.0L Kryotec Turbo Diesel',
        transmission: '6-Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Diesel',
        power_hp: 170,
        price_local: '₹26,44,000',
        on_sale: 1
    },

    // Tata Tiago
    {
        id: 'tata-tiago-in-xt',
        model_id: 'tata-tiago',
        country_code: 'IN',
        trim_name: 'XT 1.2 Revotron',
        year: 2024,
        engine: '1.2L 3-Cylinder',
        transmission: '5-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 86,
        price_local: '₹6,40,000',
        on_sale: 1
    },
    {
        id: 'tata-tiago-in-ev-xz',
        model_id: 'tata-tiago',
        country_code: 'IN',
        trim_name: 'EV XZ Plus Tech LUX',
        year: 2024,
        engine: 'Electric Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 74,
        price_local: '₹11,89,000',
        on_sale: 1
    },

    // Tesla Model 3
    {
        id: 'tesla-model3-us-lr',
        model_id: 'tesla-model-3',
        country_code: 'US',
        trim_name: 'Long Range AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 394,
        price_local: '$47,740',
        on_sale: 1
    },
    {
        id: 'tesla-model3-us-perf',
        model_id: 'tesla-model-3',
        country_code: 'US',
        trim_name: 'Performance AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 510,
        price_local: '$54,990',
        on_sale: 1
    },
    {
        id: 'tesla-model3-de-rwd',
        model_id: 'tesla-model-3',
        country_code: 'DE',
        trim_name: 'Standard RWD',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 283,
        price_local: '€40,990',
        on_sale: 1
    },
    {
        id: 'tesla-model3-uk-lr',
        model_id: 'tesla-model-3',
        country_code: 'UK',
        trim_name: 'Long Range AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 394,
        price_local: '£49,990',
        on_sale: 1
    },
    {
        id: 'tesla-model3-cn-rwd',
        model_id: 'tesla-model-3',
        country_code: 'CN',
        trim_name: 'Standard Range RWD',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 264,
        price_local: '¥245,900',
        on_sale: 1
    },
    {
        id: 'tesla-model3-au-rwd',
        model_id: 'tesla-model-3',
        country_code: 'AU',
        trim_name: 'Rear-Wheel Drive',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 283,
        price_local: 'A$58,900',
        on_sale: 1
    },
    {
        id: 'tesla-model3-ae-lr',
        model_id: 'tesla-model-3',
        country_code: 'AE',
        trim_name: 'Long Range AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 394,
        price_local: 'AED 184,990',
        on_sale: 1
    },

    // Tesla Model Y
    {
        id: 'tesla-modely-us-lr',
        model_id: 'tesla-model-y',
        country_code: 'US',
        trim_name: 'Long Range AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 384,
        price_local: '$47,990',
        on_sale: 1
    },
    {
        id: 'tesla-modely-de-perf',
        model_id: 'tesla-model-y',
        country_code: 'DE',
        trim_name: 'Performance AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 456,
        price_local: '€55,990',
        on_sale: 1
    },
    {
        id: 'tesla-modely-cn-rwd',
        model_id: 'tesla-model-y',
        country_code: 'CN',
        trim_name: 'Rear-Wheel Drive',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 299,
        price_local: '¥249,900',
        on_sale: 1
    },

    // Tesla Cybertruck
    {
        id: 'tesla-cybertruck-us-awd',
        model_id: 'tesla-cybertruck',
        country_code: 'US',
        trim_name: 'Foundation Series AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 600,
        price_local: '$99,990',
        on_sale: 1
    },

    // Ford F-150
    {
        id: 'ford-f150-us-lariat',
        model_id: 'ford-f-150',
        country_code: 'US',
        trim_name: 'Lariat SuperCrew',
        year: 2024,
        engine: '3.5L EcoBoost V6',
        transmission: '10-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Gasoline',
        power_hp: 400,
        price_local: '$65,305',
        on_sale: 1
    },
    {
        id: 'ford-f150-ae-raptor',
        model_id: 'ford-f-150',
        country_code: 'AE',
        trim_name: 'Raptor High',
        year: 2024,
        engine: '3.5L High-Output EcoBoost V6',
        transmission: '10-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Gasoline',
        power_hp: 450,
        price_local: 'AED 385,000',
        on_sale: 1
    },

    // Ford Mustang
    {
        id: 'ford-mustang-us-gt',
        model_id: 'ford-mustang',
        country_code: 'US',
        trim_name: 'GT Premium Fastback',
        year: 2024,
        engine: '5.0L Coyote V8',
        transmission: '6-Speed Manual',
        drivetrain: 'RWD',
        fuel_type: 'Gasoline',
        power_hp: 486,
        price_local: '$47,330',
        on_sale: 1
    },
    {
        id: 'ford-mustang-de-gt',
        model_id: 'ford-mustang',
        country_code: 'DE',
        trim_name: 'GT Fastback 5.0 V8',
        year: 2024,
        engine: '5.0L Coyote V8',
        transmission: '10-Speed Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Gasoline',
        power_hp: 446,
        price_local: '€63,000',
        on_sale: 1
    },
    {
        id: 'ford-mustang-au-gt',
        model_id: 'ford-mustang',
        country_code: 'AU',
        trim_name: 'GT Fastback',
        year: 2024,
        engine: '5.0L Coyote V8',
        transmission: '10-Speed Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Gasoline',
        power_hp: 486,
        price_local: 'A$77,002',
        on_sale: 1
    },

    // Ford Ranger
    {
        id: 'ford-ranger-br-limited',
        model_id: 'ford-ranger',
        country_code: 'BR',
        trim_name: 'Limited 3.0 V6 4WD',
        year: 2024,
        engine: '3.0L V6 Turbo Diesel',
        transmission: '10-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Diesel',
        power_hp: 250,
        price_local: 'R$ 319,990',
        on_sale: 1
    },
    {
        id: 'ford-ranger-au-wildtrak',
        model_id: 'ford-ranger',
        country_code: 'AU',
        trim_name: 'Wildtrak V6 4x4',
        year: 2024,
        engine: '3.0L V6 Turbo Diesel',
        transmission: '10-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Diesel',
        power_hp: 250,
        price_local: 'A$73,590',
        on_sale: 1
    },
    {
        id: 'ford-ranger-uk-raptor',
        model_id: 'ford-ranger',
        country_code: 'UK',
        trim_name: 'Raptor 3.0 EcoBoost',
        year: 2024,
        engine: '3.0L EcoBoost V6',
        transmission: '10-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Gasoline',
        power_hp: 292,
        price_local: '£59,500',
        on_sale: 1
    },

    // BMW 3 Series
    {
        id: 'bmw-3series-de-320i',
        model_id: 'bmw-3-series',
        country_code: 'DE',
        trim_name: '320i Sedan',
        year: 2024,
        engine: '2.0L TwinPower Turbo I4',
        transmission: '8-Speed Steptronic',
        drivetrain: 'RWD',
        fuel_type: 'Gasoline',
        power_hp: 184,
        price_local: '€46,800',
        on_sale: 1
    },
    {
        id: 'bmw-3series-us-m340i',
        model_id: 'bmw-3-series',
        country_code: 'US',
        trim_name: 'M340i xDrive',
        year: 2024,
        engine: '3.0L Turbo I6 Mild Hybrid',
        transmission: '8-Speed Sport Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 382,
        price_local: '$59,600',
        on_sale: 1
    },
    {
        id: 'bmw-3series-uk-330e',
        model_id: 'bmw-3-series',
        country_code: 'UK',
        trim_name: '330e M Sport',
        year: 2024,
        engine: '2.0L Plug-in Hybrid',
        transmission: '8-Speed Steptronic',
        drivetrain: 'RWD',
        fuel_type: 'PHEV',
        power_hp: 292,
        price_local: '£48,255',
        on_sale: 1
    },
    {
        id: 'bmw-3series-jp-320d',
        model_id: 'bmw-3-series',
        country_code: 'JP',
        trim_name: '320d xDrive M Sport',
        year: 2024,
        engine: '2.0L Turbo Diesel',
        transmission: '8-Speed Steptronic',
        drivetrain: 'AWD',
        fuel_type: 'Diesel',
        power_hp: 190,
        price_local: '¥6,680,000',
        on_sale: 1
    },
    {
        id: 'bmw-3series-ae-330i',
        model_id: 'bmw-3-series',
        country_code: 'AE',
        trim_name: '330i M Sport',
        year: 2024,
        engine: '2.0L TwinPower Turbo I4',
        transmission: '8-Speed Steptronic',
        drivetrain: 'RWD',
        fuel_type: 'Gasoline',
        power_hp: 255,
        price_local: 'AED 245,000',
        on_sale: 1
    },

    // BMW X5
    {
        id: 'bmw-x5-de-xdrive40i',
        model_id: 'bmw-x5',
        country_code: 'DE',
        trim_name: 'xDrive40i',
        year: 2024,
        engine: '3.0L Turbo I6 Mild Hybrid',
        transmission: '8-Speed Steptronic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 381,
        price_local: '€89,300',
        on_sale: 1
    },
    {
        id: 'bmw-x5-us-xdrive40i',
        model_id: 'bmw-x5',
        country_code: 'US',
        trim_name: 'xDrive40i AWD',
        year: 2024,
        engine: '3.0L Turbo I6 Mild Hybrid',
        transmission: '8-Speed Sport Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 375,
        price_local: '$67,500',
        on_sale: 1
    },
    {
        id: 'bmw-x5-ae-m60i',
        model_id: 'bmw-x5',
        country_code: 'AE',
        trim_name: 'M60i xDrive',
        year: 2024,
        engine: '4.4L Twin-Turbo V8 Mild Hybrid',
        transmission: '8-Speed Sport Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 530,
        price_local: 'AED 460,000',
        on_sale: 1
    },
    {
        id: 'bmw-x5-cn-xdrive40li',
        model_id: 'bmw-x5',
        country_code: 'CN',
        trim_name: 'xDrive40Li M Sport',
        year: 2024,
        engine: '3.0L Turbo I6',
        transmission: '8-Speed Steptronic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 381,
        price_local: '¥729,000',
        on_sale: 1
    },

    // BMW i4
    {
        id: 'bmw-i4-de-edrive40',
        model_id: 'bmw-i4',
        country_code: 'DE',
        trim_name: 'eDrive40 Gran Coupe',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 340,
        price_local: '€59,500',
        on_sale: 1
    },

    // BYD Atto 3
    {
        id: 'byd-atto3-cn-flagship',
        model_id: 'byd-atto-3',
        country_code: 'CN',
        trim_name: 'Yuan PLUS Flagship Plus',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 204,
        price_local: '¥147,800',
        on_sale: 1
    },
    {
        id: 'byd-atto3-au-extended',
        model_id: 'byd-atto-3',
        country_code: 'AU',
        trim_name: 'Extended Range',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 204,
        price_local: 'A$47,499',
        on_sale: 1
    },
    {
        id: 'byd-atto3-br-ev',
        model_id: 'byd-atto-3',
        country_code: 'BR',
        trim_name: 'Yuan Plus EV 60kWh',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 204,
        price_local: 'R$ 229,800',
        on_sale: 1
    },
    {
        id: 'byd-atto3-in-superior',
        model_id: 'byd-atto-3',
        country_code: 'IN',
        trim_name: 'Superior Extended Range',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 201,
        price_local: '₹33,99,000',
        on_sale: 1
    },
    {
        id: 'byd-atto3-uk-design',
        model_id: 'byd-atto-3',
        country_code: 'UK',
        trim_name: 'Design 60.5kWh',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 204,
        price_local: '£38,990',
        on_sale: 1
    },
    {
        id: 'byd-atto3-de-comfort',
        model_id: 'byd-atto-3',
        country_code: 'DE',
        trim_name: 'Comfort 60.5kWh',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 204,
        price_local: '€37,990',
        on_sale: 1
    },

    // BYD Seal
    {
        id: 'byd-seal-cn-awd',
        model_id: 'byd-seal',
        country_code: 'CN',
        trim_name: 'Performance AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 530,
        price_local: '¥249,800',
        on_sale: 1
    },
    {
        id: 'byd-seal-de-design',
        model_id: 'byd-seal',
        country_code: 'DE',
        trim_name: 'Design RWD',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 313,
        price_local: '€47,560',
        on_sale: 1
    },
    {
        id: 'byd-seal-in-performance',
        model_id: 'byd-seal',
        country_code: 'IN',
        trim_name: 'Performance AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 530,
        price_local: '₹53,00,000',
        on_sale: 1
    },
    {
        id: 'byd-seal-au-premium',
        model_id: 'byd-seal',
        country_code: 'AU',
        trim_name: 'Premium Extended Range',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 313,
        price_local: 'A$58,798',
        on_sale: 1
    },

    // BYD Dolphin
    {
        id: 'byd-dolphin-cn-knight',
        model_id: 'byd-dolphin',
        country_code: 'CN',
        trim_name: 'Knight Edition',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 177,
        price_local: '¥129,800',
        on_sale: 1
    },
    {
        id: 'byd-dolphin-br-plus',
        model_id: 'byd-dolphin',
        country_code: 'BR',
        trim_name: 'Plus 60.48kWh',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 204,
        price_local: 'R$ 179,800',
        on_sale: 1
    },
    {
        id: 'byd-dolphin-uk-comfort',
        model_id: 'byd-dolphin',
        country_code: 'UK',
        trim_name: 'Comfort 60.4kWh',
        year: 2024,
        engine: 'Permanent Magnet Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 204,
        price_local: '£30,190',
        on_sale: 1
    },

    // Volkswagen Golf
    {
        id: 'vw-golf-de-life',
        model_id: 'volkswagen-golf',
        country_code: 'DE',
        trim_name: 'Life 1.5 eTSI',
        year: 2024,
        engine: '1.5L eTSI Mild Hybrid',
        transmission: '7-Speed DSG',
        drivetrain: 'FWD',
        fuel_type: 'Mild Hybrid',
        power_hp: 150,
        price_local: '€31,195',
        on_sale: 1
    },
    {
        id: 'vw-golf-uk-gti',
        model_id: 'volkswagen-golf',
        country_code: 'UK',
        trim_name: 'GTI 2.0 TSI',
        year: 2024,
        engine: '2.0L TSI Turbo',
        transmission: '7-Speed DSG',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 265,
        price_local: '£39,400',
        on_sale: 1
    },
    {
        id: 'vw-golf-jp-tdi',
        model_id: 'volkswagen-golf',
        country_code: 'JP',
        trim_name: 'TDI Active Advance',
        year: 2024,
        engine: '2.0L TDI Diesel Turbo',
        transmission: '7-Speed DSG',
        drivetrain: 'FWD',
        fuel_type: 'Diesel',
        power_hp: 150,
        price_local: '¥4,510,000',
        on_sale: 1
    },
    {
        id: 'vw-golf-au-r',
        model_id: 'volkswagen-golf',
        country_code: 'AU',
        trim_name: 'Golf R 4MOTION',
        year: 2024,
        engine: '2.0L TSI Turbo',
        transmission: '7-Speed DSG',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 320,
        price_local: 'A$70,590',
        on_sale: 1
    },

    // Volkswagen Tiguan
    {
        id: 'vw-tiguan-us-se',
        model_id: 'volkswagen-tiguan',
        country_code: 'US',
        trim_name: 'SE 2.0T FWD',
        year: 2024,
        engine: '2.0L Turbo I4',
        transmission: '8-Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 184,
        price_local: '$31,580',
        on_sale: 1
    },
    {
        id: 'vw-tiguan-de-elegance',
        model_id: 'volkswagen-tiguan',
        country_code: 'DE',
        trim_name: 'Elegance 2.0 TDI 4MOTION',
        year: 2024,
        engine: '2.0L TDI Diesel Turbo',
        transmission: '7-Speed DSG',
        drivetrain: 'AWD',
        fuel_type: 'Diesel',
        power_hp: 193,
        price_local: '€49,435',
        on_sale: 1
    },
    {
        id: 'vw-tiguan-br-rline',
        model_id: 'volkswagen-tiguan',
        country_code: 'BR',
        trim_name: 'Allspace R-Line 300 TSI',
        year: 2024,
        engine: '2.0L TSI Turbo',
        transmission: '8-Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 186,
        price_local: 'R$ 284,590',
        on_sale: 1
    },

    // Volkswagen Polo
    {
        id: 'vw-polo-br-track',
        model_id: 'volkswagen-polo',
        country_code: 'BR',
        trim_name: 'Track 1.0 MPI Flex',
        year: 2024,
        engine: '1.0L 3-Cylinder Flex',
        transmission: '5-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Flex',
        power_hp: 84,
        price_local: 'R$ 87,990',
        on_sale: 1
    },
    {
        id: 'vw-polo-br-gts',
        model_id: 'volkswagen-polo',
        country_code: 'BR',
        trim_name: 'GTS 250 TSI Flex',
        year: 2024,
        engine: '1.4L TSI Turbo Flex',
        transmission: '6-Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Flex',
        power_hp: 150,
        price_local: 'R$ 153,790',
        on_sale: 1
    },
    {
        id: 'vw-polo-de-style',
        model_id: 'volkswagen-polo',
        country_code: 'DE',
        trim_name: 'Style 1.0 TSI',
        year: 2024,
        engine: '1.0L TSI Turbo',
        transmission: '7-Speed DSG',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 110,
        price_local: '€27,450',
        on_sale: 1
    },

    // Maruti Suzuki Swift
    {
        id: 'maruti-swift-in-lxi',
        model_id: 'maruti-suzuki-swift',
        country_code: 'IN',
        trim_name: 'LXi 1.2 MT',
        year: 2024,
        engine: '1.2L Z12E 3-Cylinder',
        transmission: '5-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 82,
        price_local: '₹6,49,000',
        on_sale: 1
    },
    {
        id: 'maruti-swift-in-zxi',
        model_id: 'maruti-suzuki-swift',
        country_code: 'IN',
        trim_name: 'ZXi Plus Dual Tone AMT',
        year: 2024,
        engine: '1.2L Z12E 3-Cylinder',
        transmission: '5-Speed AMT',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 82,
        price_local: '₹9,64,000',
        on_sale: 1
    },
    {
        id: 'maruti-swift-jp-hybrid',
        model_id: 'maruti-suzuki-swift',
        country_code: 'JP',
        trim_name: 'Hybrid MZ 2WD',
        year: 2024,
        engine: '1.2L Mild Hybrid',
        transmission: 'CVT',
        drivetrain: 'FWD',
        fuel_type: 'Mild Hybrid',
        power_hp: 82,
        price_local: '¥2,167,000',
        on_sale: 1
    },

    // Maruti Suzuki Brezza
    {
        id: 'maruti-brezza-in-vxi',
        model_id: 'maruti-suzuki-brezza',
        country_code: 'IN',
        trim_name: 'VXi 1.5 MT',
        year: 2024,
        engine: '1.5L K15C DualJet',
        transmission: '5-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 103,
        price_local: '₹9,69,500',
        on_sale: 1
    },
    {
        id: 'maruti-brezza-in-zxi',
        model_id: 'maruti-suzuki-brezza',
        country_code: 'IN',
        trim_name: 'ZXi Plus AT',
        year: 2024,
        engine: '1.5L K15C DualJet',
        transmission: '6-Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 103,
        price_local: '₹13,98,000',
        on_sale: 1
    },

    // Maruti Suzuki Grand Vitara
    {
        id: 'maruti-grandvitara-in-alpha',
        model_id: 'maruti-suzuki-grand-vitara',
        country_code: 'IN',
        trim_name: 'Alpha Plus Strong Hybrid eCVT',
        year: 2024,
        engine: '1.5L Intelligent Electric Hybrid',
        transmission: 'eCVT',
        drivetrain: 'FWD',
        fuel_type: 'Hybrid',
        power_hp: 116,
        price_local: '₹19,97,000',
        on_sale: 1
    },

    // Mahindra Scorpio-N
    {
        id: 'mahindra-scorpio-in-z4',
        model_id: 'mahindra-scorpio-n',
        country_code: 'IN',
        trim_name: 'Z4 2.2 Diesel 2WD MT',
        year: 2024,
        engine: '2.2L mHawk Turbo Diesel',
        transmission: '6-Speed Manual',
        drivetrain: 'RWD',
        fuel_type: 'Diesel',
        power_hp: 175,
        price_local: '₹15,65,000',
        on_sale: 1
    },
    {
        id: 'mahindra-scorpio-in-z8l',
        model_id: 'mahindra-scorpio-n',
        country_code: 'IN',
        trim_name: 'Z8L 4WD AT Diesel',
        year: 2024,
        engine: '2.2L mHawk Turbo Diesel',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Diesel',
        power_hp: 175,
        price_local: '₹24,54,000',
        on_sale: 1
    },
    {
        id: 'mahindra-scorpio-au-z8l',
        model_id: 'mahindra-scorpio-n',
        country_code: 'AU',
        trim_name: 'Z8L 4Xplor AT',
        year: 2024,
        engine: '2.2L mHawk Turbo Diesel',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Diesel',
        power_hp: 175,
        price_local: 'A$45,990',
        on_sale: 1
    },
    {
        id: 'mahindra-scorpio-ae-z8',
        model_id: 'mahindra-scorpio-n',
        country_code: 'AE',
        trim_name: 'Z8 2.0 Turbo Petrol 4WD',
        year: 2024,
        engine: '2.0L mStallion TGDi Turbo Petrol',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Gasoline',
        power_hp: 200,
        price_local: 'AED 99,000',
        on_sale: 1
    },

    // Mahindra XUV700
    {
        id: 'mahindra-xuv700-in-ax5',
        model_id: 'mahindra-xuv700',
        country_code: 'IN',
        trim_name: 'AX5 2.0 Petrol MT',
        year: 2024,
        engine: '2.0L mStallion TGDi Turbo Petrol',
        transmission: '6-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 200,
        price_local: '₹17,69,000',
        on_sale: 1
    },
    {
        id: 'mahindra-xuv700-in-ax7l',
        model_id: 'mahindra-xuv700',
        country_code: 'IN',
        trim_name: 'AX7L AWD AT Diesel',
        year: 2024,
        engine: '2.2L mHawk Turbo Diesel',
        transmission: '6-Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Diesel',
        power_hp: 185,
        price_local: '₹26,99,000',
        on_sale: 1
    },
    {
        id: 'mahindra-xuv700-au-ax7l',
        model_id: 'mahindra-xuv700',
        country_code: 'AU',
        trim_name: 'AX7L 2.0T AT',
        year: 2024,
        engine: '2.0L mStallion TGDi Turbo Petrol',
        transmission: '6-Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 200,
        price_local: 'A$39,990',
        on_sale: 1
    },

    // Mahindra Thar
    {
        id: 'mahindra-thar-in-lx-diesel',
        model_id: 'mahindra-thar',
        country_code: 'IN',
        trim_name: 'LX Hard Top 4WD Diesel AT',
        year: 2024,
        engine: '2.2L mHawk 130 CRDe',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Diesel',
        power_hp: 130,
        price_local: '₹17,60,000',
        on_sale: 1
    },
    {
        id: 'mahindra-thar-in-earth',
        model_id: 'mahindra-thar',
        country_code: 'IN',
        trim_name: 'Earth Edition 4WD Petrol AT',
        year: 2024,
        engine: '2.0L mStallion 150 TGDi',
        transmission: '6-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Petrol',
        power_hp: 150,
        price_local: '₹16,99,000',
        on_sale: 1
    },

    // Hyundai Creta
    {
        id: 'hyundai-creta-in-ex',
        model_id: 'hyundai-creta',
        country_code: 'IN',
        trim_name: 'EX 1.5 Petrol MT',
        year: 2024,
        engine: '1.5L MPi Petrol',
        transmission: '6-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 115,
        price_local: '₹12,21,000',
        on_sale: 1
    },
    {
        id: 'hyundai-creta-in-sx',
        model_id: 'hyundai-creta',
        country_code: 'IN',
        trim_name: 'SX(O) 1.5 Turbo DCT',
        year: 2024,
        engine: '1.5L Turbo GDi Petrol',
        transmission: '7-Speed DCT',
        drivetrain: 'FWD',
        fuel_type: 'Petrol',
        power_hp: 160,
        price_local: '₹20,00,000',
        on_sale: 1
    },
    {
        id: 'hyundai-creta-br-ultimate',
        model_id: 'hyundai-creta',
        country_code: 'BR',
        trim_name: 'Ultimate 2.0 Smartstream Flex',
        year: 2024,
        engine: '2.0L Smartstream Flex',
        transmission: '6-Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Flex',
        power_hp: 167,
        price_local: 'R$ 179,890',
        on_sale: 1
    },
    {
        id: 'hyundai-creta-ae-smart',
        model_id: 'hyundai-creta',
        country_code: 'AE',
        trim_name: 'Smart 1.5L CVT',
        year: 2024,
        engine: '1.5L Smartstream Petrol',
        transmission: 'IVT Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 115,
        price_local: 'AED 72,000',
        on_sale: 1
    },

    // Hyundai IONIQ 5
    {
        id: 'hyundai-ioniq5-us-sel',
        model_id: 'hyundai-ioniq-5',
        country_code: 'US',
        trim_name: 'SEL RWD',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Reduction Gear',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 225,
        price_local: '$47,400',
        on_sale: 1
    },
    {
        id: 'hyundai-ioniq5-us-limited',
        model_id: 'hyundai-ioniq-5',
        country_code: 'US',
        trim_name: 'Limited AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Reduction Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 320,
        price_local: '$53,500',
        on_sale: 1
    },
    {
        id: 'hyundai-ioniq5-de-n',
        model_id: 'hyundai-ioniq-5',
        country_code: 'DE',
        trim_name: 'IONIQ 5 N AWD',
        year: 2024,
        engine: 'Dual Motor Electric High Performance',
        transmission: 'Single Speed Reduction Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 650,
        price_local: '€74,900',
        on_sale: 1
    },
    {
        id: 'hyundai-ioniq5-uk-ultimate',
        model_id: 'hyundai-ioniq-5',
        country_code: 'UK',
        trim_name: 'Ultimate 77.4kWh AWD',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Reduction Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 325,
        price_local: '£50,945',
        on_sale: 1
    },
    {
        id: 'hyundai-ioniq5-au-dynamiq',
        model_id: 'hyundai-ioniq-5',
        country_code: 'AU',
        trim_name: 'Dynamiq RWD',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Reduction Gear',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 228,
        price_local: 'A$72,000',
        on_sale: 1
    },

    // Hyundai Tucson
    {
        id: 'hyundai-tucson-us-sel',
        model_id: 'hyundai-tucson',
        country_code: 'US',
        trim_name: 'SEL Convenience AWD',
        year: 2024,
        engine: '2.5L 4-Cylinder',
        transmission: '8-Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 187,
        price_local: '$32,650',
        on_sale: 1
    },
    {
        id: 'hyundai-tucson-de-phev',
        model_id: 'hyundai-tucson',
        country_code: 'DE',
        trim_name: 'Prime 1.6 T-GDI Plug-in Hybrid',
        year: 2024,
        engine: '1.6L T-GDI PHEV',
        transmission: '6-Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'PHEV',
        power_hp: 265,
        price_local: '€47,590',
        on_sale: 1
    },

    // Toyota Camry
    {
        id: 'toyota-camry-us-le',
        model_id: 'toyota-camry',
        country_code: 'US',
        trim_name: 'LE Hybrid',
        year: 2025,
        engine: '2.5L 4-Cylinder Hybrid',
        transmission: 'eCVT',
        drivetrain: 'FWD',
        fuel_type: 'Hybrid',
        power_hp: 225,
        price_local: '$28,400',
        on_sale: 1
    },

    // Tesla Model S & X
    {
        id: 'tesla-models-us-plaid',
        model_id: 'tesla-model-s',
        country_code: 'US',
        trim_name: 'Plaid Tri-Motor',
        year: 2024,
        engine: 'Tri-Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 1020,
        price_local: '$89,990',
        on_sale: 1
    },
    {
        id: 'tesla-modelx-us-lr',
        model_id: 'tesla-model-x',
        country_code: 'US',
        trim_name: 'Long Range Dual Motor',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 670,
        price_local: '$79,990',
        on_sale: 1
    },

    // Chevrolet
    {
        id: 'chevrolet-corvette-us-3lt',
        model_id: 'chevrolet-corvette',
        country_code: 'US',
        trim_name: '3LT Coupe',
        year: 2024,
        engine: '6.2L LT2 V8',
        transmission: '8-Speed Dual-Clutch',
        drivetrain: 'RWD',
        fuel_type: 'Gasoline',
        power_hp: 495,
        price_local: '$79,850',
        on_sale: 1
    },
    {
        id: 'chevrolet-silverado-us-rst',
        model_id: 'chevrolet-silverado',
        country_code: 'US',
        trim_name: 'RST 5.3L V8 4WD',
        year: 2024,
        engine: '5.3L EcoTec3 V8',
        transmission: '10-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Gasoline',
        power_hp: 355,
        price_local: '$54,300',
        on_sale: 1
    },

    // Mercedes-Benz
    {
        id: 'mercedes-cclass-de-c200',
        model_id: 'mercedes-benz-c-class',
        country_code: 'DE',
        trim_name: 'C 200 Sedan Mild Hybrid',
        year: 2024,
        engine: '1.5L Turbo I4 Mild Hybrid',
        transmission: '9G-TRONIC Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Mild Hybrid',
        power_hp: 204,
        price_local: '€49,474',
        on_sale: 1
    },
    {
        id: 'mercedes-eqe-de-350',
        model_id: 'mercedes-benz-eqe',
        country_code: 'DE',
        trim_name: 'EQE 350+ SUV',
        year: 2024,
        engine: 'Single Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Electric',
        power_hp: 292,
        price_local: '€83,478',
        on_sale: 1
    },

    // Audi
    {
        id: 'audi-a4-de-40tfsi',
        model_id: 'audi-a4',
        country_code: 'DE',
        trim_name: '40 TFSI S tronic',
        year: 2024,
        engine: '2.0L TFSI Turbo Mild Hybrid',
        transmission: '7-Speed S tronic',
        drivetrain: 'FWD',
        fuel_type: 'Mild Hybrid',
        power_hp: 204,
        price_local: '€42,500',
        on_sale: 1
    },
    {
        id: 'audi-etrongt-us-rs',
        model_id: 'audi-e-tron-gt',
        country_code: 'US',
        trim_name: 'RS e-tron GT',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: '2-Speed Automatic Rear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 637,
        price_local: '$147,100',
        on_sale: 1
    },

    // Honda
    {
        id: 'honda-civic-us-touring',
        model_id: 'honda-civic',
        country_code: 'US',
        trim_name: 'Touring Sedan',
        year: 2024,
        engine: '1.5L Turbocharged 4-Cylinder',
        transmission: 'LL-CVT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 180,
        price_local: '$30,550',
        on_sale: 1
    },
    {
        id: 'honda-crv-jp-ehev',
        model_id: 'honda-cr-v',
        country_code: 'JP',
        trim_name: 'e:HEV EX Black Edition',
        year: 2024,
        engine: '2.0L Direct Injection Hybrid',
        transmission: 'eCVT',
        drivetrain: 'AWD',
        fuel_type: 'Hybrid',
        power_hp: 204,
        price_local: '¥4,650,000',
        on_sale: 1
    },

    // Nissan
    {
        id: 'nissan-gtr-jp-nismo',
        model_id: 'nissan-gt-r',
        country_code: 'JP',
        trim_name: 'NISMO Special Edition',
        year: 2024,
        engine: '3.8L Twin-Turbo V6 VR38DETT',
        transmission: '6-Speed Dual Clutch',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 600,
        price_local: '¥30,613,000',
        on_sale: 1
    },
    {
        id: 'nissan-ariya-us-empower',
        model_id: 'nissan-ariya',
        country_code: 'US',
        trim_name: 'EMPOWER+ FWD',
        year: 2024,
        engine: 'Single AC Synchronous Motor',
        transmission: 'Single Speed Automatic',
        drivetrain: 'FWD',
        fuel_type: 'Electric',
        power_hp: 238,
        price_local: '$47,690',
        on_sale: 1
    },

    // Geely
    {
        id: 'geely-coolray-cn-flagship',
        model_id: 'geely-coolray',
        country_code: 'CN',
        trim_name: 'Binyue Cool Champion',
        year: 2024,
        engine: '1.5L TD 4-Cylinder Turbo',
        transmission: '7-Speed Wet DCT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 181,
        price_local: '¥95,800',
        on_sale: 1
    },
    {
        id: 'geely-coolray-ae-gf-sport',
        model_id: 'geely-coolray',
        country_code: 'AE',
        trim_name: 'GF Sport 1.5T',
        year: 2024,
        engine: '1.5L Turbocharged 4-Cylinder',
        transmission: '7-Speed DCT',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 174,
        price_local: 'AED 67,500',
        on_sale: 1
    },

    // Additional Multi-Market Trims for Complete Coverage
    {
        id: 'toyota-camry-us-se',
        model_id: 'toyota-camry',
        country_code: 'US',
        trim_name: 'SE AWD Hybrid',
        year: 2025,
        engine: '2.5L 4-Cylinder Hybrid',
        transmission: 'eCVT',
        drivetrain: 'AWD',
        fuel_type: 'Hybrid',
        power_hp: 232,
        price_local: '$32,225',
        on_sale: 1
    },
    {
        id: 'toyota-camry-jp-g',
        model_id: 'toyota-camry',
        country_code: 'JP',
        trim_name: 'G Leather Package',
        year: 2024,
        engine: '2.5L THS II Hybrid',
        transmission: 'eCVT',
        drivetrain: 'E-Four',
        fuel_type: 'Hybrid',
        power_hp: 218,
        price_local: '¥4,364,000',
        on_sale: 1
    },
    {
        id: 'toyota-camry-ae-limited',
        model_id: 'toyota-camry',
        country_code: 'AE',
        trim_name: 'LUMIERE 2.5L Hybrid',
        year: 2024,
        engine: '2.5L 4-Cylinder Hybrid',
        transmission: 'eCVT',
        drivetrain: 'FWD',
        fuel_type: 'Hybrid',
        power_hp: 215,
        price_local: 'AED 139,900',
        on_sale: 1
    },

    // Tesla Model S & X (EU / Global)
    {
        id: 'tesla-models-de-lr',
        model_id: 'tesla-model-s',
        country_code: 'DE',
        trim_name: 'Maximale Reichweite Allradantrieb',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 670,
        price_local: '€94,990',
        on_sale: 1
    },
    {
        id: 'tesla-modelx-de-plaid',
        model_id: 'tesla-model-x',
        country_code: 'DE',
        trim_name: 'Plaid Tri-Motor',
        year: 2024,
        engine: 'Tri-Motor Electric',
        transmission: 'Single Speed Fixed Gear',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 1020,
        price_local: '€114,990',
        on_sale: 1
    },

    // Chevrolet Global Trims
    {
        id: 'chevrolet-corvette-ae-z06',
        model_id: 'chevrolet-corvette',
        country_code: 'AE',
        trim_name: 'Z06 3LZ Coupe',
        year: 2024,
        engine: '5.5L LT6 Flat-Plane Crank V8',
        transmission: '8-Speed Dual-Clutch',
        drivetrain: 'RWD',
        fuel_type: 'Gasoline',
        power_hp: 670,
        price_local: 'AED 595,000',
        on_sale: 1
    },
    {
        id: 'chevrolet-silverado-br-highcountry',
        model_id: 'chevrolet-silverado',
        country_code: 'BR',
        trim_name: 'High Country 6.2 V8 4x4',
        year: 2024,
        engine: '6.2L EcoTec3 V8',
        transmission: '10-Speed Automatic',
        drivetrain: '4WD',
        fuel_type: 'Gasoline',
        power_hp: 426,
        price_local: 'R$ 529,990',
        on_sale: 1
    },

    // Mercedes-Benz Global Trims
    {
        id: 'mercedes-cclass-us-c300',
        model_id: 'mercedes-benz-c-class',
        country_code: 'US',
        trim_name: 'C 300 4MATIC Sedan',
        year: 2024,
        engine: '2.0L Turbo I4 Mild Hybrid',
        transmission: '9G-TRONIC Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Mild Hybrid',
        power_hp: 255,
        price_local: '$48,990',
        on_sale: 1
    },
    {
        id: 'mercedes-cclass-uk-amg',
        model_id: 'mercedes-benz-c-class',
        country_code: 'UK',
        trim_name: 'AMG Line Premium 2.0 d',
        year: 2024,
        engine: '2.0L Turbo Diesel Mild Hybrid',
        transmission: '9G-TRONIC Automatic',
        drivetrain: 'RWD',
        fuel_type: 'Diesel',
        power_hp: 200,
        price_local: '£46,700',
        on_sale: 1
    },
    {
        id: 'mercedes-eqe-us-3504m',
        model_id: 'mercedes-benz-eqe',
        country_code: 'US',
        trim_name: 'EQE 350 4MATIC SUV',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 288,
        price_local: '$77,900',
        on_sale: 1
    },

    // Audi Global Trims
    {
        id: 'audi-a4-us-45tfsi',
        model_id: 'audi-a4',
        country_code: 'US',
        trim_name: '45 TFSI quattro Premium',
        year: 2024,
        engine: '2.0L Turbocharged 4-Cylinder',
        transmission: '7-Speed S tronic',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 261,
        price_local: '$44,100',
        on_sale: 1
    },
    {
        id: 'audi-etrongt-de-quattro',
        model_id: 'audi-e-tron-gt',
        country_code: 'DE',
        trim_name: 'e-tron GT quattro',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: '2-Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 530,
        price_local: '€106,000',
        on_sale: 1
    },

    // Honda Global Trims
    {
        id: 'honda-civic-jp-type-r',
        model_id: 'honda-civic',
        country_code: 'JP',
        trim_name: 'TYPE R 2.0L VTEC Turbo',
        year: 2024,
        engine: '2.0L VTEC Turbo K20C1',
        transmission: '6-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Gasoline',
        power_hp: 330,
        price_local: '¥4,997,300',
        on_sale: 1
    },
    {
        id: 'honda-civic-in-zx',
        model_id: 'honda-civic',
        country_code: 'IN',
        trim_name: 'ZX i-DTEC Diesel',
        year: 2024,
        engine: '1.6L i-DTEC Turbo Diesel',
        transmission: '6-Speed Manual',
        drivetrain: 'FWD',
        fuel_type: 'Diesel',
        power_hp: 120,
        price_local: '₹22,35,000',
        on_sale: 1
    },
    {
        id: 'honda-crv-us-sporthyorid',
        model_id: 'honda-cr-v',
        country_code: 'US',
        trim_name: 'Sport Touring Hybrid AWD',
        year: 2024,
        engine: '2.0L 4-Cylinder Hybrid',
        transmission: 'eCVT',
        drivetrain: 'AWD',
        fuel_type: 'Hybrid',
        power_hp: 204,
        price_local: '$40,200',
        on_sale: 1
    },

    // Nissan Global Trims
    {
        id: 'nissan-gtr-us-premium',
        model_id: 'nissan-gt-r',
        country_code: 'US',
        trim_name: 'Premium 3.8L V6',
        year: 2024,
        engine: '3.8L Twin-Turbo V6 VR38DETT',
        transmission: '6-Speed Dual Clutch',
        drivetrain: 'AWD',
        fuel_type: 'Gasoline',
        power_hp: 565,
        price_local: '$121,090',
        on_sale: 1
    },
    {
        id: 'nissan-ariya-de-evolve',
        model_id: 'nissan-ariya',
        country_code: 'DE',
        trim_name: 'Evolve+ e-4ORCE 87kWh',
        year: 2024,
        engine: 'Dual Motor Electric',
        transmission: 'Single Speed Automatic',
        drivetrain: 'AWD',
        fuel_type: 'Electric',
        power_hp: 388,
        price_local: '€65,490',
        on_sale: 1
    }
];



export default {
    countries,
    manufacturers,
    models,
    trims
};
